autoLinkIssue: true
autoCloseIssue: true

branchName: '${issue.number}-${issue.title}'
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: fix/
  - label : '*'
    prefix: issue/
