branchName: "${issue.number}-${issue.title}"
autoLinkIssue: true
autoCloseIssue: true
gitSafeReplacementChar: "-"
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: fix/
  - label : '*'
    prefix: issue/
