# name: Create Issue Branch
# on:
#     issues:
#         types: [opened]

# jobs:
#     create_issue_branch_job:
#         runs-on: ubuntu-latest
#         steps:
#         - name: Create Issue Branch
#           id: Create_Issue_Branch
#           uses: robvanderleek/create-issue-branch@main
#           env:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: pm / issues

on:
  issues:
    types: [opened, assigned]

env:
  PROJECT_BOARD: "TakeShape"
  ICEBOX_COLUMN_NAME: "Icebox"
  STARTED_COLUMN_NAME: "In Progress"
  BEFORE_REVIEW_COLUMN_NAME: "Waiting on Review"

jobs:
  create-issue-branch:
    name: "create issue branch"
    runs-on: ubuntu-latest
    if: github.event.action == 'assigned'
    steps:
      - name: create the issue branch
        uses: robvanderleek/create-issue-branch@main
        id: create-issue-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: choose a pr template
        if: steps.create-issue-branch.outputs.branchName != ''
        id: template
        env:
          BRANCH_NAME: ${{ steps.create-issue-branch.outputs.branchName }}
        run: |
          branch=$BRANCH_NAME
          if [[ $branch =~ ^fix/ ]]; then \
            template="bug.md"; \
          elif [[ $branch =~ ^feat/ ]]; then \
            template="feature.md"; \
          elif [[ $branch =~ ^chore/ ]]; then \
            template="chore.md"; \
          elif [[ $branch =~ ^docs/ ]]; then \
            template="documentation.md"; \
          fi
          echo "::set-output name=template-name::$template"

      - name: add pr link in comment
        uses: mshick/add-pr-comment@v2
        if: steps.create-issue-branch.outputs.branchName != ''
        env:
          PULL_REQUEST_URL: ${{ format('https://github.com/{0}/compare/{1}...{2}?quick_pull=1&template={3}', github.repository, github.event.repository.default_branch, steps.create-issue-branch.outputs.branchName, steps.template.outputs.template-name) }}
          TEMPLATE: ${{ steps.template.outputs.template-name }}
        with:
          message: |
            ## Pull Request ![](https://raw.githubusercontent.com/primer/octicons/master/icons/git-pull-request-16.svg)

            [Create a pull request](${{ env.PULL_REQUEST_URL }}) for the issue branch using the `${{ env.TEMPLATE }}` template.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
